### PR TITLE
Add minutes for 2020-01-11.

### PR DESCRIPTION
**Pull request by Bren2010**

### CODE REVIEW

**Comment by Bren2010** [comment]
@seanturner

**Review by beurdouche — COMMENTED** [review]
Thanks for the minutes @Bren2010 ; I am confident that you can reflect in at the end of the minutes that I am "supportive of the change in the near future, as long as we are confident that we understand the difference between the current scheme (which has a security proof) and the new scheme." My rejection at the end of the conversation was more about the process aspect of trying to push it in last minute than the mechanism itself. I just want to take a bit of time to understand it, that's all...

**Comment by Bren2010** [comment]
@katrielalex Since you were minute taker on the 12th, can you integrate Ben's feedback into your notes?

**Comment by katrielalex** [comment]
Yup, I'll add it when I merge my minutes. Feel free to merge this branch and I'll get another PR up in a day or two (shortly heading to the airport).

**Comment by seanturner** [comment]
@grittygrease any issues with merging this?

**Review by seanturner — APPROVED** [review]

**Comment by katrielalex** [comment]
@Bren2010 I added you to the (dropbox paper) doc with the second day's minutes, and made sure they reflect Benjamin's final comments.

Could you either merge this PR or add the second-day minutes to it? Either way is good for me

**Pull request merged**
